### ISSUE TITLE
OreDictEntryManager flags no longer save

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/OreDict#28]
I'm not really sure when this started, but it seems the flags no longer save.

**Comment by Alexia** [comment]
…ItemName called at /home/hydra/public_html/extensions/OreDict/OreDict.body.php (415)
…ItemName called at /home/hydra/public_html/extensions/OreDict/OreDict.body.php (239)
…t::exec called at /home/hydra/public_html/extensions/OreDict/OreDict.hooks.php (185)
in OreDictHooks::RenderParser called at ? (?)
…l_user_func_array called at /home/hydra/public_html/includes/parser/Parser.php (3789)
…allParserFunction called at /home/hydra/public_html/includes/parser/Parser.php (3523)
…itution called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1177)
…at /home/hydra/public_html/extensions/ParserFunctions/ParserFunctions_body.php (104)
in ExtParserFunctions::ifObj called at ? (?)
…l_user_func_array called at /home/hydra/public_html/includes/parser/Parser.php (3789)
…allParserFunction called at /home/hydra/public_html/includes/parser/Parser.php (3523)
…itution called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1177)
…Frame_DOM::expand called at /home/hydra/public_html/includes/parser/Parser.php (3665)
…itution called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1177)
…:expand called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1687)
…rgument called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1695)
…_DOM::getArgument called at /home/hydra/public_html/includes/parser/Parser.php (4161)
…itution called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1196)
…:expand called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1675)
…rgument called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1693)

**Comment by elifoster** [comment]
Semi-related, on the live wiki, saving non-standard (207) flags seems to just randomly select flag values and get crazy values like -301.

**Comment by elifoster** [comment]
Pushing this back so we can have a different bugfix update pushed out sooner.

**Comment by elifoster** [comment]
Flags are not a thing anymore.
