### ISSUE TITLE
Licensing and Repository Ownership [OreDict]

### ISSUE THREAD

**Issue by Alexia** [FTB-Gamepedia/OreDict#41]
There are two legal issues need to be taken care of by the end of next week.

1.) Licensing
There was discussion on the #gamepedia IRC channel previously about this.  I forget what the final open source license was decided on and if it was for OreDict or Tilesheets.

The company(Curse Inc.) is requesting to be able to use OreDict under the MIT license.  However, if not MIT then GPLv2 would be acceptable.

Preferably the license would be included in the repository in the root folder titled similar to "LICENSE" in all capital letters.

* [x] @elifoster
* [x] @Alexia 
* [x] @applehat 
* [x] @Telshin 
* [x] @noahm 
* [x] @xbony2 
* [x] @retep998 

2.) Repository Ownership
Even though OreDict is used primarily on a Gamepedia wiki the primary maintainers of the OreDict project are not Curse employees or contractors.  As such legal has informed us that it would be best that the repository ownership be officially transfer to either the personal Github account of a primary maintainer or a an organization account controlled by the primary maintainers.  I will facilitate transferring the repository to the location decided.

**Comment by xbony2** [comment]
If you are going to move it, move it to the [FTB-Gamepedia group](https://github.com/FTB-Gamepedia). It's where we host our bots/libraries/other software.

**Comment by elifoster** [comment]
I'm cool with the MIT license. The discussion was about HeaderCount.

**Comment by retep998** [comment]
I am okay with MIT.

**Comment by Alexia** [comment]
Outside of Curse employees it appears that @elifoster and @xbony2 are the primary contributors, correct?

If so then I can go ahead with moving this repository over to the FTB-Gamepedia group.

**Comment by elifoster** [comment]
I wouldn't say Bony is a primary contributor, pretty sure he just did some localization. But yeah, I'm okay with it being moved to FTB-Gamepedia.

**Comment by Alexia** [comment]
@elifoster, you will have to perform the transfer since I do not have access to the FTB-Gamepedia group.

**Comment by Telshin** [comment]
I am okay with the switch to MIT and moving the project.

**Comment by applehat** [comment]
I'm good with this.

**Comment by noahm** [comment]
I'm happy with an MIT license

**Comment by xbony2** [comment]
You have my permission.

**Comment by Jinbobo** [comment]
i do not care what license this is released under. I request, however, to include me in a CONTRIBUTORS file in both repos with appropriate credit for my work.
