### ISSUE TITLE
OreDict log still has flags

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/OreDict#47]
For example: `10:35, 6 August 2017 SatanicBot (talk | contribs | block | points) created entry #43095 (Uranium Ingot from Artifice) and assigned it to the ingotUran tag and set the bits $9. (Importing entries.) `

Flags were removed a while ago. I guess I forgot to update the log format.

**Comment by xbony2** [comment]
Note that it's overwritten in the MediaWiki: namespace [here](https://ftb.gamepedia.com/MediaWiki:Logentry-oredict-createentry). Still seems to be in the English i18n file though.

**Comment by elifoster** [comment]
Thanks for pointing that out, I was not aware.
