### ISSUE TITLE
OreDict entry creation has no input validation

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/OreDict#53]
The creation functionality does not perform any checks against the data provided so you can literally put nothing and it will create an entry.

**Comment by Alexia** [comment]
I will hold off deploying the current OreDict until this is ready.

**Comment by elifoster** [comment]
Hm. Upon further investigation this is actually true for the ImportOreDict page too. This also actually brings us back to an old issue, #21, regarding the validation of mod abbreviation inputs.

I think the checks implemented should be as follows:
* tag name: non-empty
* item name: non-empty

Regarding the mod abbreviation, I don't know what an adequate check would be. We actually don't perform any checks on the information passed to Tilesheets either ([see also](https://github.com/FTB-Gamepedia/Tilesheets/blob/master/special/SheetManager.php#L140-L162)).

Regarding the grid params, I also don't know what an adequate check would be. It's not used much to begin with. Do we need any checks for this?

@retep998

**Comment by retep998** [comment]
We should definitely verify that the tag name and item name are non-empty and not just whitespace. Grid parameters are optional so we don't need any sort of check on them.

**Comment by elifoster** [comment]
What about the mod abbreviation?

**Comment by retep998** [comment]
That too. The mod abbreviation definitely should be required and non-empty and not just whitespace.

**Comment by elifoster** [comment]
Should we provide any additional checks on it though? I know there are specific requirements the tilesheet program (ftb-rs) has that are not actually enforced in either extension.

**Comment by elifoster** [comment]
Okay, I looked a bit into stuff. The tag name, item name, and mod abbreviation cannot have any characters that are invalid for a title. They must match [`$wgLegalTitleChars`](https://www.mediawiki.org/wiki/Manual:$wgLegalTitleChars). See also FTB-Gamepedia/Tilesheets#72.
