### ISSUE TITLE
"Entry already exists and no changes were made" message shows after new entry created

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/OreDict#58]
This is highly confusing.

**Comment by elifoster** [comment]
What do you mean? Can you be more descriptive?

**Comment by xbony2** [comment]
Make a new Ore Dictionary entry and you'll see what I mean.

**Comment by elifoster** [comment]
Create it using what? The API? The OreDictEntryManager? The ImportOreDict page?

**Comment by xbony2** [comment]
the ore dict entry manager

**Comment by elifoster** [comment]
Ah yes, I just had to do this and it indeed makes no sense.
